networks:
	inception:
		driver: bridge

services:
	nginx:
		build: ./requirements/nginx
		container_name: nginx_inception
		restart: always
		ports:
			- "443:443"
		volumes:
			- ./srcs/nginx/conf.d:/etc/nginx/conf.d
			- ./srcs/nginx/ssl:/etc/nginx/ssl
		networks:
			- inception

	mariadb:
		build: ./requirements/mariadb
		container_name: mariadb_inception
		restart: on-failure
		ports:
      - "3306:3306"
		env_file:
			- .env
		volumes:
			- mariadb_data:/var/lib/mysql
			- ./init.sql:/docker-entrypoint-initdb.d/init.sql
			- ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
		networks:
			- inception

volumes:
	mariadb_data:

